### ISSUE TITLE
Install error on ESXi 7.0.3 build 20328353

### ISSUE THREAD

**Issue by scorn242** [DrDonk/esxi-unlocker#11]
Hi!

![unlock run error](https://user-images.githubusercontent.com/117200129/199292531-3ea70ed8-9888-456c-b0ca-8ea1447d051b.jpg)
![check result post unlock execution](https://user-images.githubusercontent.com/117200129/199292561-9cff7781-b97f-403f-8acb-62027f37ff3b.jpg)

Have you come across a check error even though the version is the expected one?

Also,I am seeing an install error during unlock in the VMKCTL module.

Version screen is below

![version screen](https://user-images.githubusercontent.com/117200129/199293267-7048da70-569b-4c6b-9af6-e9584cbc674e.jpg)

Thank you kindly,
Scott.

**Comment by alclonky** [comment]
did you start the unlocker from an datastore?

**Comment by scorn242** [comment]
Yes. I chose the /tmp directory and set all the files properties to 7777 after upload using WinSCP in order to give them the correct permissions. This is the same directory that I used to run 3.0.1 unlocker for the previous versions of the macOS.

Note that before I attempted to run 4.0.3, I ran the 3.0.1 uninstaller esxi-uninstall.sh from the same /tmp directory.

**Comment by DrDonk** [comment]
/tmp is not a datastore folder and it’s properties seem to have changed such that there are permission errors. Move the unlocker to a datastore folder and try again.

I will see if there is a check I can add to ensure it is run from a folder that can accept the correct permissions.

**Comment by DrDonk** [comment]
I remembered that /tmp mount is too small to hold all the files for unlock process. It is usually 262144 KiB which is smaller than all the files and work files needed to create the VMTAR file.

There was a bug in check which will now report if the system has not been successfully patched. Fixed in next version.

**Comment by scorn242** [comment]
Hi. Firstly, thank you David for the advice. The install went through well and I am attempting an install of Ventura as I type.
My assumption that if 3.0.1 worked in /tmp then 4.0.3 would also work is obviously wrong, so thanks again.

Is it an expected behaviour that a previously installed (using 3.0.1) version of macOS (earlier than Ventura) would not run and become "disconnected"?

**Comment by DrDonk** [comment]
Never heard of that disconnected issue. Also there are problems with Ventura on VMware so do not be surprised if it does not work. VMware have dropped support for macOS as host and guests.

Version 4 patches more files and it breaks the file system limit on /tmp. I can't find a good way to check for VMFS file system, but if and when I do I will try and catch the issue and stop the unlocker.

**Comment by scorn242** [comment]
Well here are some results. After a successful 4.0.3 unlock install and using a freshly created Ventura installer ISO (non-Beta), the install routine goes into kernel panic after the first phase is completed -> copying files to the virtual HDD. However for a Catalina installer ISO, the install routine completes successfully on the same ESXi 7.0.3g environment.

The same Ventura ISO installs successfully on VMWare workstation (using the unlocker for Workstation v 3.0). Catalina also installs on the same unlocked VMWare Workstation environment.

Just thought to pass along my findings if interested.

**Comment by DrDonk** [comment]
It's definitely hit and miss with regards to Ventura. It was evening breaking on my real Ma running under Fusion.

There is one line in the V MX file you could try editing when the VM is powered off.

Set the ethernet device to vmxnet3 rather than e1000e, and give it another go on ESXi.

There are new version of Fusion and Workstation coming soon (probably this month) so can see if there is anything changed..

All the version 3 and 4 patches do the same thing it's just I was asked to try and remove some depenedencies such as Python for Windows and Linux unlocker. Under the hood 3 and 4 do the same thing.

**Comment by DrDonk** [comment]
There are reports now coming in of Ventura issues on VMware Workstation as well and I suspect it may be due to Apple dropping older CPU support from the kernel.

I don't have anything else I can suggest at the moment apart from wait and see what the next version of Fusion brings this month.

**Comment by scorn242** [comment]
All good and thank you for doing what you have done.
