### ISSUE TITLE
ESXI 6.7 unlock problem

### ISSUE THREAD

**Issue by lxitdn** [DrDonk/esxi-unlocker#6]
ESXI 6.7 unlock problem, I want to modify the ESXI6.7 ISO file, instead of installing ESXI to unlock, how can I modify the ESXI IOS file? Install ESX directly, you can install OSX directly，Can I integrate the modified OSX file into the BIOS or the ISO installation package?

**Comment by DrDonk** [comment]
Sorry I do not really understand wehat you want to do. What is the ESXi IOS file?

**Comment by lxitdn** [comment]
> Sorry I do not really understand what you want to do. What is the ESXi IOS file?

Sorry, I am wrong, it is an ISO file, I want to directly modify the ISO file to support OSX, so you don't need to unlock it after installation, you can install OSX directly.

**Comment by lxitdn** [comment]
![tim 20181104101810](https://user-images.githubusercontent.com/16263881/47959291-f5a80180-e01a-11e8-9e14-0d55145a7c98.jpg)
I want to modify this image file to support OSX without having to unlock it after installation.

**Comment by DrDonk** [comment]
It is possible to remaster the ISO using VMware Image Builder and there is an example here https://www.altaro.com/vmware/esxi-image-vmware-image-builder/.

This is not something I wanted to do as it can cause problems with newer versions due to certifcates and signing of some of the core components of ESXi. Feel free to try but I don't have the knowledge to do this, and also I do not have the time.
